import {
  LayoutDashboard,
  Users,
  Briefcase,
  ShoppingCart,
  CreditCard,
  Shield,
  Wallet,
  Tag,
  Bell,
  MessageSquare,
  FileText,
  Settings,
  Key,
  Activity,
  AlertCircle,
  LogOut,
} from 'lucide-react'

export const adminNavItems = [
  { label: 'Dashboard', path: '/admin', icon: LayoutDashboard },
  { label: 'User Management', path: '/admin/users', icon: Users },
  { label: 'Challenges', path: '/admin/challenges', icon: Briefcase },
  { label: 'Orders', path: '/admin/orders', icon: ShoppingCart },
  { label: 'Trading Accounts', path: '/admin/trading-accounts', icon: CreditCard },
  { label: 'KYC Verification', path: '/admin/kyc', icon: Shield },
  { label: 'Payouts', path: '/admin/payouts', icon: Wallet },
  { label: 'Coupons', path: '/admin/coupons', icon: Tag },
  { label: 'Announcements', path: '/admin/announcements', icon: Bell },
  { label: 'Support Tickets', path: '/admin/support', icon: MessageSquare },
  { label: 'CMS', path: '/admin/cms', icon: FileText },
  { label: 'Payment Gateway', path: '/admin/payment-settings', icon: Key },
  { label: 'Integrations', path: '/admin/integrations', icon: Settings },
  { label: 'Security', path: '/admin/security', icon: Shield },
  { label: 'Activity Logs', path: '/admin/activity-logs', icon: Activity },
  { label: 'Error Logs', path: '/admin/error-logs', icon: AlertCircle },
  { label: 'Logout', path: '/admin/logout', icon: LogOut },
]

